server:
  port: 8080
  shutdown: graceful
spring:
  application:
    name: electronic-server
  profiles:
    active: dev
logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql打印
    call-setters-on-nulls: true
  mapperLocations:
    - classpath*:/mapper/**/*.xml
    - classpath*:/modeler-mybatis-mappings/**/*.xml
#swagger配置
swagger:
  host:
  service:
    url: http://swagger.io/
    title: 智能设备控制接口
    des: 智能设备控制api文档